### ISSUE TITLE
User management and `git`

### ISSUE THREAD

**Issue by mainrs** [lukebfox/nix-configs#1]
Hello! First off, I do really like your configuration layout and have adopted it when switched to flakes.
I was wondering how exactly you manage git credentials (username and email) for different users?

I have two different users that both have different git credentials. My idea was to add new fields to
`user-manager` that are git-specific. But it seems that it's not possible to change the `config` of
`home-manager` modules inside of a `NixOS` module.

I've found this like but can't figure out where the username comes from: https://github.com/lukebfox/nix-configs/blob/5432ca7dead6d39fca9b9772fc3c10914ba6969f/profiles/home-manager/developer/default.nix#L4

**Comment by lukebfox** [comment]
Hey sorry for the late reply. If you're still interested or for anyone else reading, user data is contained in `./data/shared.toml`. This data is converted from toml into nix:
https://github.com/lukebfox/nix-configs/blob/60c64f14c2212b181fc2819c438b7cfe696bc86d/flake.nix#L41-L42
At the nixos config level, user profiles are imported:
https://github.com/lukebfox/nix-configs/blob/60c64f14c2212b181fc2819c438b7cfe696bc86d/configs/nixos/medusa.nix#L14-L20
User profiles mainly configure the nixos [user-manager](https://github.com/lukebfox/nix-configs/blob/60c64f14c2212b181fc2819c438b7cfe696bc86d/modules/nixos/user-manager/default.nix) module from this repo. 
https://github.com/lukebfox/nix-configs/blob/60c64f14c2212b181fc2819c438b7cfe696bc86d/profiles/nixos/users/lukebfox/default.nix#L3-L10
The user-manager module implementation takes configuration and defines both the nixos and home-manager user configuration:
https://github.com/lukebfox/nix-configs/blob/60c64f14c2212b181fc2819c438b7cfe696bc86d/modules/nixos/user-manager/default.nix#L78-L104
The username in nixos/home-manager user configs comes from the attrname of the config e.g `lukebfox` (this is vanilla nixos/home-manager user module stuff). In the home manager `developer` profile I set some user specific git config:
https://github.com/lukebfox/nix-configs/blob/5432ca7dead6d39fca9b9772fc3c10914ba6969f/profiles/home-manager/developer/default.nix#L1-L7
https://github.com/lukebfox/nix-configs/blob/5432ca7dead6d39fca9b9772fc3c10914ba6969f/profiles/home-manager/developer/default.nix#L20-L25

**Comment by lukebfox** [comment]
If you want to use user data more often when writing home-manager configurations, you can add data to shared.toml, and then you can refer to `shared.users.${config.home.username}.whatever` when you are configuring whatever home-manager options you like.

**Comment by mainrs** [comment]
Thank you for the detailed explanation. This helped out a lot.
